import Header from "@/components/Header";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ActiveSectionContextProvider from "@/context/active-section-context.ts";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} dark:bg-slate-950 bg-zinc-300 bg-fixed bg-no-repeat text-black dark:text-white h-[40000px]`}
      >
        <div className="h-[400px] w-[400px] bg-emerald-400/30 absolute -z-10 blur-[10rem] rounded-full right-0"></div>
        <div className="h-[200px] w-[200px] bg-sky-500/60 absolute -z-10 blur-[10rem] rounded-full bottom-0 "></div>
        <ActiveSectionContextProvider>
          <Header />
          {children}
        </ActiveSectionContextProvider>
      </body>
    </html>
  );
}
